print('--------------------------')
print('|  01HelloWorld          |')
print('|  Name: Annmarie Thomas        |')
print('|  Version: 01           |')
print('--------------------------')
print('Hello, world!')
